Repository YeetCodes/SnowWhite, pull requests merged in 2020-04, with the labels that each got.

#16 setting up grunt, removing redundant directories
  .github/workflows/ci.yml
  .gitignore
  Gruntfile.js
  MMM-CurrencyRate/test.js
  builds/linuxmake/placeholder
  builds/placeholder
  grunt/aliases.json
  grunt/nodeunit.js
  lib/placeholder
  package.json
  placeholder
  testing/configs/modules/placeholder
  testing/placeholder
  testing/unit/functions/placeholder
Labels: setup

#17 added tests for CurrencyRate
  MMM-CurrencyRate/MMM-CurrencyRate.js
  MMM-CurrencyRate/test.js
Labels: module, testing

#21 added artifacts to CI
  .github/workflows/ci.yml
  package.json
Labels: setup

#13 Demotivator Module
  MMM-Demotivational/MMM-Demotivational.js
  MMM-Demotivational/test.js
  grunt/nodeunit.js
Labels: module

#23 Fixing Demotivator
  MMM-Demotivational/MMM-Demotivational.js
Labels: module

#34 eslint, pre-commit hook for formatter, auto-format on push
  .eslintrc.yml
  .github/workflows/ci.yml
  .github/workflows/formatter.yml
  .gitignore
  .pre-commit-config.yaml
  Gruntfile.js
  MMM-CurrencyRate/MMM-CurrencyRate.js
  MMM-CurrencyRate/README.md
  MMM-CurrencyRate/node_helper.js
  MMM-CurrencyRate/test.js
  MMM-Demotivational/MMM-Demotivational.js
  MMM-Demotivational/test.js
  MMM-Yang/MMM-Yang.js
  MMM-Yang/README.md
  MMM-Yang/test.js
  README.md
  grunt/aliases.json
  grunt/nodeunit.js
  package-lock.json
  package.json
Labels: extra tool
